In [1]:
import pandas as pd 
import numpy as np 
df1=pd.read_csv(r'C:\Users\vaish\Documents\Vaishnavi_datascience\Movie_Recommendation\movie2\tmdb_5000_credits.csv')
df2=pd.read_csv(r'C:\Users\vaish\Documents\Vaishnavi_datascience\Movie_Recommendation\movie2\tmdb_5000_movies.csv')

In [2]:
df1.columns = ['id','tittle','cast','crew']
df2= df2.merge(df1,on='id') 
#df2 shows the movie_data

In [3]:
df2.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  ... runtime  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                     tittle  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne /

In [4]:
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
df2.shape
     

(4803, 23)

In [6]:

# selecting the relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast']


In [7]:
combined_features = df2['genres']+' '+df2['keywords']+' '+df2['tagline']+' '+df2['cast']+' '
     

In [8]:
print(combined_features)
     

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800                                                  NaN
4801    [] [] A New Yorker in Shanghai [{"cast_id": 3,...
4802                                                  NaN
Length: 4803, dtype: object


In [9]:
# converting the text data to feature vectors i.e td-idf matrix

vectorizer = TfidfVectorizer()

In [10]:
# Remove rows with NaN values
combined_features = pd.Series(combined_features).dropna().tolist()

# Now you can fit_transform
feature_vectors = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 756648 stored elements and shape (3959, 208823)>
  Coords	Values
  (0, 175042)	0.31772860824986165
  (0, 40027)	0.009291722385763977
  (0, 187048)	0.31772860824986165
  (0, 151691)	0.0068640692162196424
  (0, 6523)	0.010231357935463453
  (0, 151877)	0.00785282054651941
  (0, 14962)	0.010684474687644907
  (0, 167967)	0.009628153933241254
  (0, 148400)	0.009095383910852486
  (0, 196276)	0.009000665659518176
  (0, 168506)	0.009059506252080948
  (0, 17469)	0.01976698507735127
  (0, 163061)	0.018219255196155484
  (0, 161292)	0.01915612427745426
  (0, 40403)	0.01604928958830816
  (0, 169772)	0.013621257713203511
  (0, 41583)	0.024080848374507913
  (0, 198987)	0.05505918014754871
  (0, 206311)	0.021264977839454195
  (0, 41592)	0.022041656809770622
  (0, 161772)	0.020258446760892772
  (0, 42224)	0.02257803435138258
  (0, 198635)	0.016534942915455774
  (0, 42467)	0.017210335210209902
  (0, 203035)	0.014242914604327785
  :	:
  (3958, 

In [12]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)
     

In [13]:
print(similarity)

[[1.         0.49971514 0.53975745 ... 0.27594114 0.23412432 0.24852411]
 [0.49971514 1.         0.51267876 ... 0.27532873 0.23284966 0.24280882]
 [0.53975745 0.51267876 1.         ... 0.28111252 0.2435458  0.25583832]
 ...
 [0.27594114 0.27532873 0.28111252 ... 1.         0.1282471  0.12904902]
 [0.23412432 0.23284966 0.2435458  ... 0.1282471  1.         0.11288682]
 [0.24852411 0.24280882 0.25583832 ... 0.12904902 0.11288682 1.        ]]


In [14]:
print(similarity.shape)     

(3959, 3959)


In [15]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name :  iron man


In [16]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = df2['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [17]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [18]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [19]:
# Assuming df2 is your DataFrame

# Add an 'index' column
df2 = df2.reset_index(drop=False)

# The 'index' column will now be part of the DataFrame
print(df2.head())

   index     budget                                             genres  \
0      0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1      1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2      2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3      3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4      4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...

In [20]:
df2.head(5)

index     budget                                             genres  \
0      0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1      1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2      2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3      3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4      4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                     tittle  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{

In [21]:
# finding the index of the movie with title

index_of_the_movie = df2[df2.title == close_match]['index'].values[0]
print(index_of_the_movie)

68


In [22]:

# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)
     

[(0, np.float64(0.3989169077325043)), (1, np.float64(0.3934303290423422)), (2, np.float64(0.40844785142985507)), (3, np.float64(0.4081547047974077)), (4, np.float64(0.3596348950536939)), (5, np.float64(0.4224649828682187)), (6, np.float64(0.2739655627951057)), (7, np.float64(0.37717854939835543)), (8, np.float64(0.4027566761334172)), (9, np.float64(0.45784414873189766)), (10, np.float64(0.3732855508606096)), (11, np.float64(0.39892025046456003)), (12, np.float64(0.4195715179226267)), (13, np.float64(0.39127293862177903)), (14, np.float64(0.33437550265914173)), (15, np.float64(0.4026559727533751)), (16, np.float64(0.3963803732037747)), (17, np.float64(0.3356291441410327)), (18, np.float64(0.4115001211446842)), (19, np.float64(0.41772282414974216)), (20, np.float64(0.38458318721687146)), (21, np.float64(0.38243901612763226)), (22, np.float64(0.36372623794623166)), (23, np.float64(0.3516065307007755)), (24, np.float64(0.4530059378950339)), (25, np.float64(0.39210467377012165)), (26, np.fl

In [24]:
len(similarity_score)
     

3959

In [25]:
# sorting the movies based on their similarity score
#reeverse=true means desc order
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(68, np.float64(0.9999999999999999)), (1738, np.float64(0.46353868734942244)), (356, np.float64(0.4629986316824153)), (352, np.float64(0.4603256218519458)), (63, np.float64(0.45856901102034964)), (9, np.float64(0.45784414873189766)), (69, np.float64(0.4559429740080822)), (24, np.float64(0.4530059378950339)), (274, np.float64(0.45130875361369255)), (1361, np.float64(0.450501707324463)), (313, np.float64(0.4503000105375784)), (1885, np.float64(0.44991434488728854)), (3616, np.float64(0.4498567553205538)), (1675, np.float64(0.44690258275555145)), (788, np.float64(0.44579162512094417)), (1458, np.float64(0.44551880906807745)), (1805, np.float64(0.44547190483831045)), (3287, np.float64(0.444983316257212)), (2344, np.float64(0.4443159155084059)), (821, np.float64(0.4439119589591133)), (528, np.float64(0.44382531613015624)), (121, np.float64(0.4435924446598311)), (853, np.float64(0.4417465854682588)), (1089, np.float64(0.44056255270459654)), (1833, np.float64(0.43970810524642473)), (280, np.

In [27]:
print(len(df2))
print(similarity.shape)

4803
(3959, 3959)


In [25]:
if index_of_the_movie >= similarity.shape[0]:
    print(f"Index {index_of_the_movie} is out of bounds.")
else:
    similarity_score = list(enumerate(similarity[index_of_the_movie]))
    sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=False)
    print('Movies suggested for you : None \n')

Movies suggested for you : None 



In [29]:

movie_name = input('Enter your favourite movie name: ')

list_of_all_titles = df2['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

if find_close_match:
    close_match = find_close_match[0]
    index_of_the_movie = df2[df2.title == close_match].index[0]  # Get the index of the close match

    if index_of_the_movie < similarity.shape[0]:
        
        similarity_score = list(enumerate(similarity[index_of_the_movie]))
        
        # Create a list of recommended movies with their similarity scores
        recommended_movies = []

        # Check for movies that contain the input title and add them to the recommended list
        for movie in similarity_score:
            index = movie[0]
            title_from_index = df2.iloc[index]['title']  # Get movie title
            score = movie[1]

            # Add the movie to the recommended list
            recommended_movies.append((title_from_index, score))

        prioritized_movies = sorted(recommended_movies, key=lambda x: (movie_name.lower() in x[0].lower(), x[1]), reverse=True)

    
        print('Movies suggested for you : \n')
        for i, (title, score) in enumerate(prioritized_movies):
            if i < 30:
                print(f"{i + 1}. {title}")

    else:
        print(f"No close matches found for {movie_name}")
else:
    print(f"No close matches found for {movie_name}")


Enter your favourite movie name:  iron man


Movies suggested for you : 

1. Iron Man
2. Iron Man 3
3. Iron Man 2
4. Kundun
5. Sherlock Holmes
6. Mulan
7. The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
8. Batman v Superman: Dawn of Justice
9. Hugo
10. King Kong
11. Gladiator
12. Lethal Weapon 3
13. The Peanuts Movie
14. August: Osage County
15. Robin and Marian
16. Machine Gun Preacher
17. Deadpool
18. Femme Fatale
19. The Curse of the Jade Scorpion
20. The Land Girls
21. Raging Bull
22. The Equalizer
23. Munich
24. Night at the Museum: Battle of the Smithsonian
25. Elizabeth: The Golden Age
26. The Phantom
27. Legally Blonde 2: Red, White & Blonde
28. Public Enemies
29. Casper
30. The Chronicles of Narnia: The Voyage of the Dawn Treader
